// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

public interface GrpcGetStampInformationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icheck.qr.read.grpc.GrpcGetStampInformationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
   */
  com.vertx.vuong.grpc.GrpcGetStampInformationData getData();
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
   */
  com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder getDataOrBuilder();
}
