// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

/**
 * Protobuf type {@code com.icheck.qr.read.grpc.GrpcGetStampInformationData}
 */
public  final class GrpcGetStampInformationData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.icheck.qr.read.grpc.GrpcGetStampInformationData)
    GrpcGetStampInformationDataOrBuilder {
  // Use GrpcGetStampInformationData.newBuilder() to construct.
  private GrpcGetStampInformationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcGetStampInformationData() {
    codeQRM_ = "";
    codeQRI_ = "";
    codeSMS_ = "";
    status_ = 0;
    batchName_ = "";
    exportDate_ = "";
    services_ = "";
    productName_ = "";
    productImage_ = "";
    owner_ = false;
    batchId_ = 0L;
    isBlocked_ = 0;
    prefix_ = "";
    idStart_ = 0L;
    idEnd_ = 0L;
    internalSerial_ = "";
    internalQRM_ = "";
    internalQRI_ = "";
    internalSMS_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GrpcGetStampInformationData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            codeQRM_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            codeQRI_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            codeSMS_ = s;
            break;
          }
          case 32: {

            status_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            batchName_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            exportDate_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            services_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            productName_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            productImage_ = s;
            break;
          }
          case 80: {

            owner_ = input.readBool();
            break;
          }
          case 88: {

            batchId_ = input.readInt64();
            break;
          }
          case 96: {

            isBlocked_ = input.readInt32();
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            prefix_ = s;
            break;
          }
          case 112: {

            idStart_ = input.readInt64();
            break;
          }
          case 120: {

            idEnd_ = input.readInt64();
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            internalSerial_ = s;
            break;
          }
          case 138: {
            java.lang.String s = input.readStringRequireUtf8();

            internalQRM_ = s;
            break;
          }
          case 146: {
            java.lang.String s = input.readStringRequireUtf8();

            internalQRI_ = s;
            break;
          }
          case 154: {
            java.lang.String s = input.readStringRequireUtf8();

            internalSMS_ = s;
            break;
          }
          case 162: {
            com.vertx.vuong.grpc.GrpcRestoreInfo.Builder subBuilder = null;
            if (restoreInfo_ != null) {
              subBuilder = restoreInfo_.toBuilder();
            }
            restoreInfo_ = input.readMessage(com.vertx.vuong.grpc.GrpcRestoreInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(restoreInfo_);
              restoreInfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.vertx.vuong.grpc.GrpcGetStampInformationData.class, com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder.class);
  }

  public static final int CODEQRM_FIELD_NUMBER = 1;
  private volatile java.lang.Object codeQRM_;
  /**
   * <code>string codeQRM = 1;</code>
   */
  public java.lang.String getCodeQRM() {
    java.lang.Object ref = codeQRM_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codeQRM_ = s;
      return s;
    }
  }
  /**
   * <code>string codeQRM = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCodeQRMBytes() {
    java.lang.Object ref = codeQRM_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codeQRM_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODEQRI_FIELD_NUMBER = 2;
  private volatile java.lang.Object codeQRI_;
  /**
   * <code>string codeQRI = 2;</code>
   */
  public java.lang.String getCodeQRI() {
    java.lang.Object ref = codeQRI_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codeQRI_ = s;
      return s;
    }
  }
  /**
   * <code>string codeQRI = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCodeQRIBytes() {
    java.lang.Object ref = codeQRI_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codeQRI_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CODESMS_FIELD_NUMBER = 3;
  private volatile java.lang.Object codeSMS_;
  /**
   * <code>string codeSMS = 3;</code>
   */
  public java.lang.String getCodeSMS() {
    java.lang.Object ref = codeSMS_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codeSMS_ = s;
      return s;
    }
  }
  /**
   * <code>string codeSMS = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCodeSMSBytes() {
    java.lang.Object ref = codeSMS_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codeSMS_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_;
  /**
   * <code>int32 status = 4;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int BATCHNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object batchName_;
  /**
   * <code>string batchName = 5;</code>
   */
  public java.lang.String getBatchName() {
    java.lang.Object ref = batchName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      batchName_ = s;
      return s;
    }
  }
  /**
   * <code>string batchName = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBatchNameBytes() {
    java.lang.Object ref = batchName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      batchName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPORTDATE_FIELD_NUMBER = 6;
  private volatile java.lang.Object exportDate_;
  /**
   * <code>string exportDate = 6;</code>
   */
  public java.lang.String getExportDate() {
    java.lang.Object ref = exportDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exportDate_ = s;
      return s;
    }
  }
  /**
   * <code>string exportDate = 6;</code>
   */
  public com.google.protobuf.ByteString
      getExportDateBytes() {
    java.lang.Object ref = exportDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exportDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICES_FIELD_NUMBER = 7;
  private volatile java.lang.Object services_;
  /**
   * <code>string services = 7;</code>
   */
  public java.lang.String getServices() {
    java.lang.Object ref = services_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      services_ = s;
      return s;
    }
  }
  /**
   * <code>string services = 7;</code>
   */
  public com.google.protobuf.ByteString
      getServicesBytes() {
    java.lang.Object ref = services_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      services_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTNAME_FIELD_NUMBER = 8;
  private volatile java.lang.Object productName_;
  /**
   * <code>string productName = 8;</code>
   */
  public java.lang.String getProductName() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productName_ = s;
      return s;
    }
  }
  /**
   * <code>string productName = 8;</code>
   */
  public com.google.protobuf.ByteString
      getProductNameBytes() {
    java.lang.Object ref = productName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCTIMAGE_FIELD_NUMBER = 9;
  private volatile java.lang.Object productImage_;
  /**
   * <code>string productImage = 9;</code>
   */
  public java.lang.String getProductImage() {
    java.lang.Object ref = productImage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productImage_ = s;
      return s;
    }
  }
  /**
   * <code>string productImage = 9;</code>
   */
  public com.google.protobuf.ByteString
      getProductImageBytes() {
    java.lang.Object ref = productImage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productImage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_FIELD_NUMBER = 10;
  private boolean owner_;
  /**
   * <code>bool owner = 10;</code>
   */
  public boolean getOwner() {
    return owner_;
  }

  public static final int BATCHID_FIELD_NUMBER = 11;
  private long batchId_;
  /**
   * <code>int64 batchId = 11;</code>
   */
  public long getBatchId() {
    return batchId_;
  }

  public static final int ISBLOCKED_FIELD_NUMBER = 12;
  private int isBlocked_;
  /**
   * <code>int32 isBlocked = 12;</code>
   */
  public int getIsBlocked() {
    return isBlocked_;
  }

  public static final int PREFIX_FIELD_NUMBER = 13;
  private volatile java.lang.Object prefix_;
  /**
   * <code>string prefix = 13;</code>
   */
  public java.lang.String getPrefix() {
    java.lang.Object ref = prefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prefix_ = s;
      return s;
    }
  }
  /**
   * <code>string prefix = 13;</code>
   */
  public com.google.protobuf.ByteString
      getPrefixBytes() {
    java.lang.Object ref = prefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDSTART_FIELD_NUMBER = 14;
  private long idStart_;
  /**
   * <code>int64 idStart = 14;</code>
   */
  public long getIdStart() {
    return idStart_;
  }

  public static final int IDEND_FIELD_NUMBER = 15;
  private long idEnd_;
  /**
   * <code>int64 idEnd = 15;</code>
   */
  public long getIdEnd() {
    return idEnd_;
  }

  public static final int INTERNALSERIAL_FIELD_NUMBER = 16;
  private volatile java.lang.Object internalSerial_;
  /**
   * <code>string internalSerial = 16;</code>
   */
  public java.lang.String getInternalSerial() {
    java.lang.Object ref = internalSerial_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      internalSerial_ = s;
      return s;
    }
  }
  /**
   * <code>string internalSerial = 16;</code>
   */
  public com.google.protobuf.ByteString
      getInternalSerialBytes() {
    java.lang.Object ref = internalSerial_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      internalSerial_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERNALQRM_FIELD_NUMBER = 17;
  private volatile java.lang.Object internalQRM_;
  /**
   * <code>string internalQRM = 17;</code>
   */
  public java.lang.String getInternalQRM() {
    java.lang.Object ref = internalQRM_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      internalQRM_ = s;
      return s;
    }
  }
  /**
   * <code>string internalQRM = 17;</code>
   */
  public com.google.protobuf.ByteString
      getInternalQRMBytes() {
    java.lang.Object ref = internalQRM_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      internalQRM_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERNALQRI_FIELD_NUMBER = 18;
  private volatile java.lang.Object internalQRI_;
  /**
   * <code>string internalQRI = 18;</code>
   */
  public java.lang.String getInternalQRI() {
    java.lang.Object ref = internalQRI_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      internalQRI_ = s;
      return s;
    }
  }
  /**
   * <code>string internalQRI = 18;</code>
   */
  public com.google.protobuf.ByteString
      getInternalQRIBytes() {
    java.lang.Object ref = internalQRI_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      internalQRI_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERNALSMS_FIELD_NUMBER = 19;
  private volatile java.lang.Object internalSMS_;
  /**
   * <code>string internalSMS = 19;</code>
   */
  public java.lang.String getInternalSMS() {
    java.lang.Object ref = internalSMS_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      internalSMS_ = s;
      return s;
    }
  }
  /**
   * <code>string internalSMS = 19;</code>
   */
  public com.google.protobuf.ByteString
      getInternalSMSBytes() {
    java.lang.Object ref = internalSMS_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      internalSMS_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESTOREINFO_FIELD_NUMBER = 20;
  private com.vertx.vuong.grpc.GrpcRestoreInfo restoreInfo_;
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
   */
  public boolean hasRestoreInfo() {
    return restoreInfo_ != null;
  }
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
   */
  public com.vertx.vuong.grpc.GrpcRestoreInfo getRestoreInfo() {
    return restoreInfo_ == null ? com.vertx.vuong.grpc.GrpcRestoreInfo.getDefaultInstance() : restoreInfo_;
  }
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
   */
  public com.vertx.vuong.grpc.GrpcRestoreInfoOrBuilder getRestoreInfoOrBuilder() {
    return getRestoreInfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCodeQRMBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, codeQRM_);
    }
    if (!getCodeQRIBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codeQRI_);
    }
    if (!getCodeSMSBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, codeSMS_);
    }
    if (status_ != 0) {
      output.writeInt32(4, status_);
    }
    if (!getBatchNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, batchName_);
    }
    if (!getExportDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, exportDate_);
    }
    if (!getServicesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, services_);
    }
    if (!getProductNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, productName_);
    }
    if (!getProductImageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, productImage_);
    }
    if (owner_ != false) {
      output.writeBool(10, owner_);
    }
    if (batchId_ != 0L) {
      output.writeInt64(11, batchId_);
    }
    if (isBlocked_ != 0) {
      output.writeInt32(12, isBlocked_);
    }
    if (!getPrefixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, prefix_);
    }
    if (idStart_ != 0L) {
      output.writeInt64(14, idStart_);
    }
    if (idEnd_ != 0L) {
      output.writeInt64(15, idEnd_);
    }
    if (!getInternalSerialBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, internalSerial_);
    }
    if (!getInternalQRMBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 17, internalQRM_);
    }
    if (!getInternalQRIBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 18, internalQRI_);
    }
    if (!getInternalSMSBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 19, internalSMS_);
    }
    if (restoreInfo_ != null) {
      output.writeMessage(20, getRestoreInfo());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCodeQRMBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, codeQRM_);
    }
    if (!getCodeQRIBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codeQRI_);
    }
    if (!getCodeSMSBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, codeSMS_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, status_);
    }
    if (!getBatchNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, batchName_);
    }
    if (!getExportDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, exportDate_);
    }
    if (!getServicesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, services_);
    }
    if (!getProductNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, productName_);
    }
    if (!getProductImageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, productImage_);
    }
    if (owner_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, owner_);
    }
    if (batchId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, batchId_);
    }
    if (isBlocked_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, isBlocked_);
    }
    if (!getPrefixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, prefix_);
    }
    if (idStart_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(14, idStart_);
    }
    if (idEnd_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(15, idEnd_);
    }
    if (!getInternalSerialBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, internalSerial_);
    }
    if (!getInternalQRMBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(17, internalQRM_);
    }
    if (!getInternalQRIBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(18, internalQRI_);
    }
    if (!getInternalSMSBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(19, internalSMS_);
    }
    if (restoreInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getRestoreInfo());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.vertx.vuong.grpc.GrpcGetStampInformationData)) {
      return super.equals(obj);
    }
    com.vertx.vuong.grpc.GrpcGetStampInformationData other = (com.vertx.vuong.grpc.GrpcGetStampInformationData) obj;

    boolean result = true;
    result = result && getCodeQRM()
        .equals(other.getCodeQRM());
    result = result && getCodeQRI()
        .equals(other.getCodeQRI());
    result = result && getCodeSMS()
        .equals(other.getCodeSMS());
    result = result && (getStatus()
        == other.getStatus());
    result = result && getBatchName()
        .equals(other.getBatchName());
    result = result && getExportDate()
        .equals(other.getExportDate());
    result = result && getServices()
        .equals(other.getServices());
    result = result && getProductName()
        .equals(other.getProductName());
    result = result && getProductImage()
        .equals(other.getProductImage());
    result = result && (getOwner()
        == other.getOwner());
    result = result && (getBatchId()
        == other.getBatchId());
    result = result && (getIsBlocked()
        == other.getIsBlocked());
    result = result && getPrefix()
        .equals(other.getPrefix());
    result = result && (getIdStart()
        == other.getIdStart());
    result = result && (getIdEnd()
        == other.getIdEnd());
    result = result && getInternalSerial()
        .equals(other.getInternalSerial());
    result = result && getInternalQRM()
        .equals(other.getInternalQRM());
    result = result && getInternalQRI()
        .equals(other.getInternalQRI());
    result = result && getInternalSMS()
        .equals(other.getInternalSMS());
    result = result && (hasRestoreInfo() == other.hasRestoreInfo());
    if (hasRestoreInfo()) {
      result = result && getRestoreInfo()
          .equals(other.getRestoreInfo());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODEQRM_FIELD_NUMBER;
    hash = (53 * hash) + getCodeQRM().hashCode();
    hash = (37 * hash) + CODEQRI_FIELD_NUMBER;
    hash = (53 * hash) + getCodeQRI().hashCode();
    hash = (37 * hash) + CODESMS_FIELD_NUMBER;
    hash = (53 * hash) + getCodeSMS().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + BATCHNAME_FIELD_NUMBER;
    hash = (53 * hash) + getBatchName().hashCode();
    hash = (37 * hash) + EXPORTDATE_FIELD_NUMBER;
    hash = (53 * hash) + getExportDate().hashCode();
    hash = (37 * hash) + SERVICES_FIELD_NUMBER;
    hash = (53 * hash) + getServices().hashCode();
    hash = (37 * hash) + PRODUCTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getProductName().hashCode();
    hash = (37 * hash) + PRODUCTIMAGE_FIELD_NUMBER;
    hash = (53 * hash) + getProductImage().hashCode();
    hash = (37 * hash) + OWNER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOwner());
    hash = (37 * hash) + BATCHID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getBatchId());
    hash = (37 * hash) + ISBLOCKED_FIELD_NUMBER;
    hash = (53 * hash) + getIsBlocked();
    hash = (37 * hash) + PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getPrefix().hashCode();
    hash = (37 * hash) + IDSTART_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdStart());
    hash = (37 * hash) + IDEND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getIdEnd());
    hash = (37 * hash) + INTERNALSERIAL_FIELD_NUMBER;
    hash = (53 * hash) + getInternalSerial().hashCode();
    hash = (37 * hash) + INTERNALQRM_FIELD_NUMBER;
    hash = (53 * hash) + getInternalQRM().hashCode();
    hash = (37 * hash) + INTERNALQRI_FIELD_NUMBER;
    hash = (53 * hash) + getInternalQRI().hashCode();
    hash = (37 * hash) + INTERNALSMS_FIELD_NUMBER;
    hash = (53 * hash) + getInternalSMS().hashCode();
    if (hasRestoreInfo()) {
      hash = (37 * hash) + RESTOREINFO_FIELD_NUMBER;
      hash = (53 * hash) + getRestoreInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.vertx.vuong.grpc.GrpcGetStampInformationData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.icheck.qr.read.grpc.GrpcGetStampInformationData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.icheck.qr.read.grpc.GrpcGetStampInformationData)
      com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vertx.vuong.grpc.GrpcGetStampInformationData.class, com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder.class);
    }

    // Construct using com.vertx.vuong.grpc.GrpcGetStampInformationData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      codeQRM_ = "";

      codeQRI_ = "";

      codeSMS_ = "";

      status_ = 0;

      batchName_ = "";

      exportDate_ = "";

      services_ = "";

      productName_ = "";

      productImage_ = "";

      owner_ = false;

      batchId_ = 0L;

      isBlocked_ = 0;

      prefix_ = "";

      idStart_ = 0L;

      idEnd_ = 0L;

      internalSerial_ = "";

      internalQRM_ = "";

      internalQRI_ = "";

      internalSMS_ = "";

      if (restoreInfoBuilder_ == null) {
        restoreInfo_ = null;
      } else {
        restoreInfo_ = null;
        restoreInfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_descriptor;
    }

    public com.vertx.vuong.grpc.GrpcGetStampInformationData getDefaultInstanceForType() {
      return com.vertx.vuong.grpc.GrpcGetStampInformationData.getDefaultInstance();
    }

    public com.vertx.vuong.grpc.GrpcGetStampInformationData build() {
      com.vertx.vuong.grpc.GrpcGetStampInformationData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.vertx.vuong.grpc.GrpcGetStampInformationData buildPartial() {
      com.vertx.vuong.grpc.GrpcGetStampInformationData result = new com.vertx.vuong.grpc.GrpcGetStampInformationData(this);
      result.codeQRM_ = codeQRM_;
      result.codeQRI_ = codeQRI_;
      result.codeSMS_ = codeSMS_;
      result.status_ = status_;
      result.batchName_ = batchName_;
      result.exportDate_ = exportDate_;
      result.services_ = services_;
      result.productName_ = productName_;
      result.productImage_ = productImage_;
      result.owner_ = owner_;
      result.batchId_ = batchId_;
      result.isBlocked_ = isBlocked_;
      result.prefix_ = prefix_;
      result.idStart_ = idStart_;
      result.idEnd_ = idEnd_;
      result.internalSerial_ = internalSerial_;
      result.internalQRM_ = internalQRM_;
      result.internalQRI_ = internalQRI_;
      result.internalSMS_ = internalSMS_;
      if (restoreInfoBuilder_ == null) {
        result.restoreInfo_ = restoreInfo_;
      } else {
        result.restoreInfo_ = restoreInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vertx.vuong.grpc.GrpcGetStampInformationData) {
        return mergeFrom((com.vertx.vuong.grpc.GrpcGetStampInformationData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vertx.vuong.grpc.GrpcGetStampInformationData other) {
      if (other == com.vertx.vuong.grpc.GrpcGetStampInformationData.getDefaultInstance()) return this;
      if (!other.getCodeQRM().isEmpty()) {
        codeQRM_ = other.codeQRM_;
        onChanged();
      }
      if (!other.getCodeQRI().isEmpty()) {
        codeQRI_ = other.codeQRI_;
        onChanged();
      }
      if (!other.getCodeSMS().isEmpty()) {
        codeSMS_ = other.codeSMS_;
        onChanged();
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (!other.getBatchName().isEmpty()) {
        batchName_ = other.batchName_;
        onChanged();
      }
      if (!other.getExportDate().isEmpty()) {
        exportDate_ = other.exportDate_;
        onChanged();
      }
      if (!other.getServices().isEmpty()) {
        services_ = other.services_;
        onChanged();
      }
      if (!other.getProductName().isEmpty()) {
        productName_ = other.productName_;
        onChanged();
      }
      if (!other.getProductImage().isEmpty()) {
        productImage_ = other.productImage_;
        onChanged();
      }
      if (other.getOwner() != false) {
        setOwner(other.getOwner());
      }
      if (other.getBatchId() != 0L) {
        setBatchId(other.getBatchId());
      }
      if (other.getIsBlocked() != 0) {
        setIsBlocked(other.getIsBlocked());
      }
      if (!other.getPrefix().isEmpty()) {
        prefix_ = other.prefix_;
        onChanged();
      }
      if (other.getIdStart() != 0L) {
        setIdStart(other.getIdStart());
      }
      if (other.getIdEnd() != 0L) {
        setIdEnd(other.getIdEnd());
      }
      if (!other.getInternalSerial().isEmpty()) {
        internalSerial_ = other.internalSerial_;
        onChanged();
      }
      if (!other.getInternalQRM().isEmpty()) {
        internalQRM_ = other.internalQRM_;
        onChanged();
      }
      if (!other.getInternalQRI().isEmpty()) {
        internalQRI_ = other.internalQRI_;
        onChanged();
      }
      if (!other.getInternalSMS().isEmpty()) {
        internalSMS_ = other.internalSMS_;
        onChanged();
      }
      if (other.hasRestoreInfo()) {
        mergeRestoreInfo(other.getRestoreInfo());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.vertx.vuong.grpc.GrpcGetStampInformationData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vertx.vuong.grpc.GrpcGetStampInformationData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object codeQRM_ = "";
    /**
     * <code>string codeQRM = 1;</code>
     */
    public java.lang.String getCodeQRM() {
      java.lang.Object ref = codeQRM_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codeQRM_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codeQRM = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCodeQRMBytes() {
      java.lang.Object ref = codeQRM_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codeQRM_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codeQRM = 1;</code>
     */
    public Builder setCodeQRM(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codeQRM_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codeQRM = 1;</code>
     */
    public Builder clearCodeQRM() {
      
      codeQRM_ = getDefaultInstance().getCodeQRM();
      onChanged();
      return this;
    }
    /**
     * <code>string codeQRM = 1;</code>
     */
    public Builder setCodeQRMBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codeQRM_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object codeQRI_ = "";
    /**
     * <code>string codeQRI = 2;</code>
     */
    public java.lang.String getCodeQRI() {
      java.lang.Object ref = codeQRI_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codeQRI_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codeQRI = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodeQRIBytes() {
      java.lang.Object ref = codeQRI_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codeQRI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codeQRI = 2;</code>
     */
    public Builder setCodeQRI(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codeQRI_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codeQRI = 2;</code>
     */
    public Builder clearCodeQRI() {
      
      codeQRI_ = getDefaultInstance().getCodeQRI();
      onChanged();
      return this;
    }
    /**
     * <code>string codeQRI = 2;</code>
     */
    public Builder setCodeQRIBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codeQRI_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object codeSMS_ = "";
    /**
     * <code>string codeSMS = 3;</code>
     */
    public java.lang.String getCodeSMS() {
      java.lang.Object ref = codeSMS_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codeSMS_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codeSMS = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCodeSMSBytes() {
      java.lang.Object ref = codeSMS_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codeSMS_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codeSMS = 3;</code>
     */
    public Builder setCodeSMS(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codeSMS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codeSMS = 3;</code>
     */
    public Builder clearCodeSMS() {
      
      codeSMS_ = getDefaultInstance().getCodeSMS();
      onChanged();
      return this;
    }
    /**
     * <code>string codeSMS = 3;</code>
     */
    public Builder setCodeSMSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codeSMS_ = value;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <code>int32 status = 4;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <code>int32 status = 4;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 status = 4;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object batchName_ = "";
    /**
     * <code>string batchName = 5;</code>
     */
    public java.lang.String getBatchName() {
      java.lang.Object ref = batchName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        batchName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string batchName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBatchNameBytes() {
      java.lang.Object ref = batchName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        batchName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string batchName = 5;</code>
     */
    public Builder setBatchName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      batchName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string batchName = 5;</code>
     */
    public Builder clearBatchName() {
      
      batchName_ = getDefaultInstance().getBatchName();
      onChanged();
      return this;
    }
    /**
     * <code>string batchName = 5;</code>
     */
    public Builder setBatchNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      batchName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object exportDate_ = "";
    /**
     * <code>string exportDate = 6;</code>
     */
    public java.lang.String getExportDate() {
      java.lang.Object ref = exportDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exportDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exportDate = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExportDateBytes() {
      java.lang.Object ref = exportDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exportDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exportDate = 6;</code>
     */
    public Builder setExportDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exportDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exportDate = 6;</code>
     */
    public Builder clearExportDate() {
      
      exportDate_ = getDefaultInstance().getExportDate();
      onChanged();
      return this;
    }
    /**
     * <code>string exportDate = 6;</code>
     */
    public Builder setExportDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exportDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object services_ = "";
    /**
     * <code>string services = 7;</code>
     */
    public java.lang.String getServices() {
      java.lang.Object ref = services_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        services_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string services = 7;</code>
     */
    public com.google.protobuf.ByteString
        getServicesBytes() {
      java.lang.Object ref = services_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        services_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string services = 7;</code>
     */
    public Builder setServices(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      services_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string services = 7;</code>
     */
    public Builder clearServices() {
      
      services_ = getDefaultInstance().getServices();
      onChanged();
      return this;
    }
    /**
     * <code>string services = 7;</code>
     */
    public Builder setServicesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      services_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productName_ = "";
    /**
     * <code>string productName = 8;</code>
     */
    public java.lang.String getProductName() {
      java.lang.Object ref = productName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productName = 8;</code>
     */
    public com.google.protobuf.ByteString
        getProductNameBytes() {
      java.lang.Object ref = productName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productName = 8;</code>
     */
    public Builder setProductName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 8;</code>
     */
    public Builder clearProductName() {
      
      productName_ = getDefaultInstance().getProductName();
      onChanged();
      return this;
    }
    /**
     * <code>string productName = 8;</code>
     */
    public Builder setProductNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productImage_ = "";
    /**
     * <code>string productImage = 9;</code>
     */
    public java.lang.String getProductImage() {
      java.lang.Object ref = productImage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productImage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string productImage = 9;</code>
     */
    public com.google.protobuf.ByteString
        getProductImageBytes() {
      java.lang.Object ref = productImage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string productImage = 9;</code>
     */
    public Builder setProductImage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productImage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string productImage = 9;</code>
     */
    public Builder clearProductImage() {
      
      productImage_ = getDefaultInstance().getProductImage();
      onChanged();
      return this;
    }
    /**
     * <code>string productImage = 9;</code>
     */
    public Builder setProductImageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productImage_ = value;
      onChanged();
      return this;
    }

    private boolean owner_ ;
    /**
     * <code>bool owner = 10;</code>
     */
    public boolean getOwner() {
      return owner_;
    }
    /**
     * <code>bool owner = 10;</code>
     */
    public Builder setOwner(boolean value) {
      
      owner_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool owner = 10;</code>
     */
    public Builder clearOwner() {
      
      owner_ = false;
      onChanged();
      return this;
    }

    private long batchId_ ;
    /**
     * <code>int64 batchId = 11;</code>
     */
    public long getBatchId() {
      return batchId_;
    }
    /**
     * <code>int64 batchId = 11;</code>
     */
    public Builder setBatchId(long value) {
      
      batchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 batchId = 11;</code>
     */
    public Builder clearBatchId() {
      
      batchId_ = 0L;
      onChanged();
      return this;
    }

    private int isBlocked_ ;
    /**
     * <code>int32 isBlocked = 12;</code>
     */
    public int getIsBlocked() {
      return isBlocked_;
    }
    /**
     * <code>int32 isBlocked = 12;</code>
     */
    public Builder setIsBlocked(int value) {
      
      isBlocked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 isBlocked = 12;</code>
     */
    public Builder clearIsBlocked() {
      
      isBlocked_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object prefix_ = "";
    /**
     * <code>string prefix = 13;</code>
     */
    public java.lang.String getPrefix() {
      java.lang.Object ref = prefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prefix = 13;</code>
     */
    public com.google.protobuf.ByteString
        getPrefixBytes() {
      java.lang.Object ref = prefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prefix = 13;</code>
     */
    public Builder setPrefix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prefix = 13;</code>
     */
    public Builder clearPrefix() {
      
      prefix_ = getDefaultInstance().getPrefix();
      onChanged();
      return this;
    }
    /**
     * <code>string prefix = 13;</code>
     */
    public Builder setPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prefix_ = value;
      onChanged();
      return this;
    }

    private long idStart_ ;
    /**
     * <code>int64 idStart = 14;</code>
     */
    public long getIdStart() {
      return idStart_;
    }
    /**
     * <code>int64 idStart = 14;</code>
     */
    public Builder setIdStart(long value) {
      
      idStart_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idStart = 14;</code>
     */
    public Builder clearIdStart() {
      
      idStart_ = 0L;
      onChanged();
      return this;
    }

    private long idEnd_ ;
    /**
     * <code>int64 idEnd = 15;</code>
     */
    public long getIdEnd() {
      return idEnd_;
    }
    /**
     * <code>int64 idEnd = 15;</code>
     */
    public Builder setIdEnd(long value) {
      
      idEnd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 idEnd = 15;</code>
     */
    public Builder clearIdEnd() {
      
      idEnd_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object internalSerial_ = "";
    /**
     * <code>string internalSerial = 16;</code>
     */
    public java.lang.String getInternalSerial() {
      java.lang.Object ref = internalSerial_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        internalSerial_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string internalSerial = 16;</code>
     */
    public com.google.protobuf.ByteString
        getInternalSerialBytes() {
      java.lang.Object ref = internalSerial_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string internalSerial = 16;</code>
     */
    public Builder setInternalSerial(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      internalSerial_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string internalSerial = 16;</code>
     */
    public Builder clearInternalSerial() {
      
      internalSerial_ = getDefaultInstance().getInternalSerial();
      onChanged();
      return this;
    }
    /**
     * <code>string internalSerial = 16;</code>
     */
    public Builder setInternalSerialBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      internalSerial_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object internalQRM_ = "";
    /**
     * <code>string internalQRM = 17;</code>
     */
    public java.lang.String getInternalQRM() {
      java.lang.Object ref = internalQRM_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        internalQRM_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string internalQRM = 17;</code>
     */
    public com.google.protobuf.ByteString
        getInternalQRMBytes() {
      java.lang.Object ref = internalQRM_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalQRM_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string internalQRM = 17;</code>
     */
    public Builder setInternalQRM(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      internalQRM_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string internalQRM = 17;</code>
     */
    public Builder clearInternalQRM() {
      
      internalQRM_ = getDefaultInstance().getInternalQRM();
      onChanged();
      return this;
    }
    /**
     * <code>string internalQRM = 17;</code>
     */
    public Builder setInternalQRMBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      internalQRM_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object internalQRI_ = "";
    /**
     * <code>string internalQRI = 18;</code>
     */
    public java.lang.String getInternalQRI() {
      java.lang.Object ref = internalQRI_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        internalQRI_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string internalQRI = 18;</code>
     */
    public com.google.protobuf.ByteString
        getInternalQRIBytes() {
      java.lang.Object ref = internalQRI_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalQRI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string internalQRI = 18;</code>
     */
    public Builder setInternalQRI(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      internalQRI_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string internalQRI = 18;</code>
     */
    public Builder clearInternalQRI() {
      
      internalQRI_ = getDefaultInstance().getInternalQRI();
      onChanged();
      return this;
    }
    /**
     * <code>string internalQRI = 18;</code>
     */
    public Builder setInternalQRIBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      internalQRI_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object internalSMS_ = "";
    /**
     * <code>string internalSMS = 19;</code>
     */
    public java.lang.String getInternalSMS() {
      java.lang.Object ref = internalSMS_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        internalSMS_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string internalSMS = 19;</code>
     */
    public com.google.protobuf.ByteString
        getInternalSMSBytes() {
      java.lang.Object ref = internalSMS_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalSMS_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string internalSMS = 19;</code>
     */
    public Builder setInternalSMS(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      internalSMS_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string internalSMS = 19;</code>
     */
    public Builder clearInternalSMS() {
      
      internalSMS_ = getDefaultInstance().getInternalSMS();
      onChanged();
      return this;
    }
    /**
     * <code>string internalSMS = 19;</code>
     */
    public Builder setInternalSMSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      internalSMS_ = value;
      onChanged();
      return this;
    }

    private com.vertx.vuong.grpc.GrpcRestoreInfo restoreInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.vertx.vuong.grpc.GrpcRestoreInfo, com.vertx.vuong.grpc.GrpcRestoreInfo.Builder, com.vertx.vuong.grpc.GrpcRestoreInfoOrBuilder> restoreInfoBuilder_;
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public boolean hasRestoreInfo() {
      return restoreInfoBuilder_ != null || restoreInfo_ != null;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public com.vertx.vuong.grpc.GrpcRestoreInfo getRestoreInfo() {
      if (restoreInfoBuilder_ == null) {
        return restoreInfo_ == null ? com.vertx.vuong.grpc.GrpcRestoreInfo.getDefaultInstance() : restoreInfo_;
      } else {
        return restoreInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public Builder setRestoreInfo(com.vertx.vuong.grpc.GrpcRestoreInfo value) {
      if (restoreInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        restoreInfo_ = value;
        onChanged();
      } else {
        restoreInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public Builder setRestoreInfo(
        com.vertx.vuong.grpc.GrpcRestoreInfo.Builder builderForValue) {
      if (restoreInfoBuilder_ == null) {
        restoreInfo_ = builderForValue.build();
        onChanged();
      } else {
        restoreInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public Builder mergeRestoreInfo(com.vertx.vuong.grpc.GrpcRestoreInfo value) {
      if (restoreInfoBuilder_ == null) {
        if (restoreInfo_ != null) {
          restoreInfo_ =
            com.vertx.vuong.grpc.GrpcRestoreInfo.newBuilder(restoreInfo_).mergeFrom(value).buildPartial();
        } else {
          restoreInfo_ = value;
        }
        onChanged();
      } else {
        restoreInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public Builder clearRestoreInfo() {
      if (restoreInfoBuilder_ == null) {
        restoreInfo_ = null;
        onChanged();
      } else {
        restoreInfo_ = null;
        restoreInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public com.vertx.vuong.grpc.GrpcRestoreInfo.Builder getRestoreInfoBuilder() {
      
      onChanged();
      return getRestoreInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    public com.vertx.vuong.grpc.GrpcRestoreInfoOrBuilder getRestoreInfoOrBuilder() {
      if (restoreInfoBuilder_ != null) {
        return restoreInfoBuilder_.getMessageOrBuilder();
      } else {
        return restoreInfo_ == null ?
            com.vertx.vuong.grpc.GrpcRestoreInfo.getDefaultInstance() : restoreInfo_;
      }
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.vertx.vuong.grpc.GrpcRestoreInfo, com.vertx.vuong.grpc.GrpcRestoreInfo.Builder, com.vertx.vuong.grpc.GrpcRestoreInfoOrBuilder> 
        getRestoreInfoFieldBuilder() {
      if (restoreInfoBuilder_ == null) {
        restoreInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.vertx.vuong.grpc.GrpcRestoreInfo, com.vertx.vuong.grpc.GrpcRestoreInfo.Builder, com.vertx.vuong.grpc.GrpcRestoreInfoOrBuilder>(
                getRestoreInfo(),
                getParentForChildren(),
                isClean());
        restoreInfo_ = null;
      }
      return restoreInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.icheck.qr.read.grpc.GrpcGetStampInformationData)
  }

  // @@protoc_insertion_point(class_scope:com.icheck.qr.read.grpc.GrpcGetStampInformationData)
  private static final com.vertx.vuong.grpc.GrpcGetStampInformationData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.vertx.vuong.grpc.GrpcGetStampInformationData();
  }

  public static com.vertx.vuong.grpc.GrpcGetStampInformationData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcGetStampInformationData>
      PARSER = new com.google.protobuf.AbstractParser<GrpcGetStampInformationData>() {
    public GrpcGetStampInformationData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GrpcGetStampInformationData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcGetStampInformationData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcGetStampInformationData> getParserForType() {
    return PARSER;
  }

  public com.vertx.vuong.grpc.GrpcGetStampInformationData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

