// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

public interface GrpcRestoreInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icheck.qr.read.grpc.GrpcRestoreInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reason = 1;</code>
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 1;</code>
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>int64 userCreatedById = 2;</code>
   */
  long getUserCreatedById();

  /**
   * <code>string userCreatedByName = 3;</code>
   */
  java.lang.String getUserCreatedByName();
  /**
   * <code>string userCreatedByName = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserCreatedByNameBytes();

  /**
   * <code>string createdDate = 4;</code>
   */
  java.lang.String getCreatedDate();
  /**
   * <code>string createdDate = 4;</code>
   */
  com.google.protobuf.ByteString
      getCreatedDateBytes();
}
