// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

public interface GrpcGetStampInformationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icheck.qr.read.grpc.GrpcGetStampInformationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string prefix = 1;</code>
   */
  java.lang.String getPrefix();
  /**
   * <code>string prefix = 1;</code>
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <code>int64 idStart = 2;</code>
   */
  long getIdStart();

  /**
   * <code>int64 idEnd = 3;</code>
   */
  long getIdEnd();

  /**
   * <code>int64 ownerId = 4;</code>
   */
  long getOwnerId();

  /**
   * <code>int32 excludeQr = 5;</code>
   */
  int getExcludeQr();
}
