// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

public interface GrpcGetStampInformationDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.icheck.qr.read.grpc.GrpcGetStampInformationData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string codeQRM = 1;</code>
   */
  java.lang.String getCodeQRM();
  /**
   * <code>string codeQRM = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeQRMBytes();

  /**
   * <code>string codeQRI = 2;</code>
   */
  java.lang.String getCodeQRI();
  /**
   * <code>string codeQRI = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodeQRIBytes();

  /**
   * <code>string codeSMS = 3;</code>
   */
  java.lang.String getCodeSMS();
  /**
   * <code>string codeSMS = 3;</code>
   */
  com.google.protobuf.ByteString
      getCodeSMSBytes();

  /**
   * <code>int32 status = 4;</code>
   */
  int getStatus();

  /**
   * <code>string batchName = 5;</code>
   */
  java.lang.String getBatchName();
  /**
   * <code>string batchName = 5;</code>
   */
  com.google.protobuf.ByteString
      getBatchNameBytes();

  /**
   * <code>string exportDate = 6;</code>
   */
  java.lang.String getExportDate();
  /**
   * <code>string exportDate = 6;</code>
   */
  com.google.protobuf.ByteString
      getExportDateBytes();

  /**
   * <code>string services = 7;</code>
   */
  java.lang.String getServices();
  /**
   * <code>string services = 7;</code>
   */
  com.google.protobuf.ByteString
      getServicesBytes();

  /**
   * <code>string productName = 8;</code>
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 8;</code>
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <code>string productImage = 9;</code>
   */
  java.lang.String getProductImage();
  /**
   * <code>string productImage = 9;</code>
   */
  com.google.protobuf.ByteString
      getProductImageBytes();

  /**
   * <code>bool owner = 10;</code>
   */
  boolean getOwner();

  /**
   * <code>int64 batchId = 11;</code>
   */
  long getBatchId();

  /**
   * <code>int32 isBlocked = 12;</code>
   */
  int getIsBlocked();

  /**
   * <code>string prefix = 13;</code>
   */
  java.lang.String getPrefix();
  /**
   * <code>string prefix = 13;</code>
   */
  com.google.protobuf.ByteString
      getPrefixBytes();

  /**
   * <code>int64 idStart = 14;</code>
   */
  long getIdStart();

  /**
   * <code>int64 idEnd = 15;</code>
   */
  long getIdEnd();

  /**
   * <code>string internalSerial = 16;</code>
   */
  java.lang.String getInternalSerial();
  /**
   * <code>string internalSerial = 16;</code>
   */
  com.google.protobuf.ByteString
      getInternalSerialBytes();

  /**
   * <code>string internalQRM = 17;</code>
   */
  java.lang.String getInternalQRM();
  /**
   * <code>string internalQRM = 17;</code>
   */
  com.google.protobuf.ByteString
      getInternalQRMBytes();

  /**
   * <code>string internalQRI = 18;</code>
   */
  java.lang.String getInternalQRI();
  /**
   * <code>string internalQRI = 18;</code>
   */
  com.google.protobuf.ByteString
      getInternalQRIBytes();

  /**
   * <code>string internalSMS = 19;</code>
   */
  java.lang.String getInternalSMS();
  /**
   * <code>string internalSMS = 19;</code>
   */
  com.google.protobuf.ByteString
      getInternalSMSBytes();

  /**
   * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
   */
  boolean hasRestoreInfo();
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
   */
  com.vertx.vuong.grpc.GrpcRestoreInfo getRestoreInfo();
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcRestoreInfo restoreInfo = 20;</code>
   */
  com.vertx.vuong.grpc.GrpcRestoreInfoOrBuilder getRestoreInfoOrBuilder();
}
