// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

/**
 * Protobuf type {@code com.icheck.qr.read.grpc.GrpcGetStampInformationResponse}
 */
public  final class GrpcGetStampInformationResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.icheck.qr.read.grpc.GrpcGetStampInformationResponse)
    GrpcGetStampInformationResponseOrBuilder {
  // Use GrpcGetStampInformationResponse.newBuilder() to construct.
  private GrpcGetStampInformationResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GrpcGetStampInformationResponse() {
    code_ = 0;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private GrpcGetStampInformationResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder subBuilder = null;
            if (data_ != null) {
              subBuilder = data_.toBuilder();
            }
            data_ = input.readMessage(com.vertx.vuong.grpc.GrpcGetStampInformationData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(data_);
              data_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.vertx.vuong.grpc.GrpcGetStampInformationResponse.class, com.vertx.vuong.grpc.GrpcGetStampInformationResponse.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATA_FIELD_NUMBER = 3;
  private com.vertx.vuong.grpc.GrpcGetStampInformationData data_;
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
   */
  public boolean hasData() {
    return data_ != null;
  }
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
   */
  public com.vertx.vuong.grpc.GrpcGetStampInformationData getData() {
    return data_ == null ? com.vertx.vuong.grpc.GrpcGetStampInformationData.getDefaultInstance() : data_;
  }
  /**
   * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
   */
  public com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder getDataOrBuilder() {
    return getData();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (data_ != null) {
      output.writeMessage(3, getData());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (data_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getData());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.vertx.vuong.grpc.GrpcGetStampInformationResponse)) {
      return super.equals(obj);
    }
    com.vertx.vuong.grpc.GrpcGetStampInformationResponse other = (com.vertx.vuong.grpc.GrpcGetStampInformationResponse) obj;

    boolean result = true;
    result = result && (getCode()
        == other.getCode());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (hasData() == other.hasData());
    if (hasData()) {
      result = result && getData()
          .equals(other.getData());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasData()) {
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.vertx.vuong.grpc.GrpcGetStampInformationResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.icheck.qr.read.grpc.GrpcGetStampInformationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.icheck.qr.read.grpc.GrpcGetStampInformationResponse)
      com.vertx.vuong.grpc.GrpcGetStampInformationResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vertx.vuong.grpc.GrpcGetStampInformationResponse.class, com.vertx.vuong.grpc.GrpcGetStampInformationResponse.Builder.class);
    }

    // Construct using com.vertx.vuong.grpc.GrpcGetStampInformationResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (dataBuilder_ == null) {
        data_ = null;
      } else {
        data_ = null;
        dataBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.vertx.vuong.grpc.Transfer.internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_descriptor;
    }

    public com.vertx.vuong.grpc.GrpcGetStampInformationResponse getDefaultInstanceForType() {
      return com.vertx.vuong.grpc.GrpcGetStampInformationResponse.getDefaultInstance();
    }

    public com.vertx.vuong.grpc.GrpcGetStampInformationResponse build() {
      com.vertx.vuong.grpc.GrpcGetStampInformationResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.vertx.vuong.grpc.GrpcGetStampInformationResponse buildPartial() {
      com.vertx.vuong.grpc.GrpcGetStampInformationResponse result = new com.vertx.vuong.grpc.GrpcGetStampInformationResponse(this);
      result.code_ = code_;
      result.message_ = message_;
      if (dataBuilder_ == null) {
        result.data_ = data_;
      } else {
        result.data_ = dataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.vertx.vuong.grpc.GrpcGetStampInformationResponse) {
        return mergeFrom((com.vertx.vuong.grpc.GrpcGetStampInformationResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.vertx.vuong.grpc.GrpcGetStampInformationResponse other) {
      if (other == com.vertx.vuong.grpc.GrpcGetStampInformationResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasData()) {
        mergeData(other.getData());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.vertx.vuong.grpc.GrpcGetStampInformationResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.vertx.vuong.grpc.GrpcGetStampInformationResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.vertx.vuong.grpc.GrpcGetStampInformationData data_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.vertx.vuong.grpc.GrpcGetStampInformationData, com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder, com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder> dataBuilder_;
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public boolean hasData() {
      return dataBuilder_ != null || data_ != null;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public com.vertx.vuong.grpc.GrpcGetStampInformationData getData() {
      if (dataBuilder_ == null) {
        return data_ == null ? com.vertx.vuong.grpc.GrpcGetStampInformationData.getDefaultInstance() : data_;
      } else {
        return dataBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public Builder setData(com.vertx.vuong.grpc.GrpcGetStampInformationData value) {
      if (dataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        dataBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public Builder setData(
        com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder builderForValue) {
      if (dataBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        dataBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public Builder mergeData(com.vertx.vuong.grpc.GrpcGetStampInformationData value) {
      if (dataBuilder_ == null) {
        if (data_ != null) {
          data_ =
            com.vertx.vuong.grpc.GrpcGetStampInformationData.newBuilder(data_).mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        dataBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public Builder clearData() {
      if (dataBuilder_ == null) {
        data_ = null;
        onChanged();
      } else {
        data_ = null;
        dataBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder getDataBuilder() {
      
      onChanged();
      return getDataFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    public com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder getDataOrBuilder() {
      if (dataBuilder_ != null) {
        return dataBuilder_.getMessageOrBuilder();
      } else {
        return data_ == null ?
            com.vertx.vuong.grpc.GrpcGetStampInformationData.getDefaultInstance() : data_;
      }
    }
    /**
     * <code>.com.icheck.qr.read.grpc.GrpcGetStampInformationData data = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.vertx.vuong.grpc.GrpcGetStampInformationData, com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder, com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder> 
        getDataFieldBuilder() {
      if (dataBuilder_ == null) {
        dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.vertx.vuong.grpc.GrpcGetStampInformationData, com.vertx.vuong.grpc.GrpcGetStampInformationData.Builder, com.vertx.vuong.grpc.GrpcGetStampInformationDataOrBuilder>(
                getData(),
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      return dataBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.icheck.qr.read.grpc.GrpcGetStampInformationResponse)
  }

  // @@protoc_insertion_point(class_scope:com.icheck.qr.read.grpc.GrpcGetStampInformationResponse)
  private static final com.vertx.vuong.grpc.GrpcGetStampInformationResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.vertx.vuong.grpc.GrpcGetStampInformationResponse();
  }

  public static com.vertx.vuong.grpc.GrpcGetStampInformationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GrpcGetStampInformationResponse>
      PARSER = new com.google.protobuf.AbstractParser<GrpcGetStampInformationResponse>() {
    public GrpcGetStampInformationResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new GrpcGetStampInformationResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GrpcGetStampInformationResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GrpcGetStampInformationResponse> getParserForType() {
    return PARSER;
  }

  public com.vertx.vuong.grpc.GrpcGetStampInformationResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

