// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transfer.proto

package com.vertx.vuong.grpc;

public final class Transfer {
  private Transfer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_icheck_qr_read_grpc_GrpcRestoreInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_icheck_qr_read_grpc_GrpcRestoreInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016transfer.proto\022\027com.icheck.qr.read.grp" +
      "c\"t\n\036GrpcGetStampInformationRequest\022\016\n\006p" +
      "refix\030\001 \001(\t\022\017\n\007idStart\030\002 \001(\003\022\r\n\005idEnd\030\003 " +
      "\001(\003\022\017\n\007ownerId\030\004 \001(\003\022\021\n\texcludeQr\030\005 \001(\005\"" +
      "\204\001\n\037GrpcGetStampInformationResponse\022\014\n\004c" +
      "ode\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\022B\n\004data\030\003 \001(\013" +
      "24.com.icheck.qr.read.grpc.GrpcGetStampI" +
      "nformationData\"\275\003\n\033GrpcGetStampInformati" +
      "onData\022\017\n\007codeQRM\030\001 \001(\t\022\017\n\007codeQRI\030\002 \001(\t" +
      "\022\017\n\007codeSMS\030\003 \001(\t\022\016\n\006status\030\004 \001(\005\022\021\n\tbat",
      "chName\030\005 \001(\t\022\022\n\nexportDate\030\006 \001(\t\022\020\n\010serv" +
      "ices\030\007 \001(\t\022\023\n\013productName\030\010 \001(\t\022\024\n\014produ" +
      "ctImage\030\t \001(\t\022\r\n\005owner\030\n \001(\010\022\017\n\007batchId\030" +
      "\013 \001(\003\022\021\n\tisBlocked\030\014 \001(\005\022\016\n\006prefix\030\r \001(\t" +
      "\022\017\n\007idStart\030\016 \001(\003\022\r\n\005idEnd\030\017 \001(\003\022\026\n\016inte" +
      "rnalSerial\030\020 \001(\t\022\023\n\013internalQRM\030\021 \001(\t\022\023\n" +
      "\013internalQRI\030\022 \001(\t\022\023\n\013internalSMS\030\023 \001(\t\022" +
      "=\n\013restoreInfo\030\024 \001(\0132(.com.icheck.qr.rea" +
      "d.grpc.GrpcRestoreInfo\"j\n\017GrpcRestoreInf" +
      "o\022\016\n\006reason\030\001 \001(\t\022\027\n\017userCreatedById\030\002 \001",
      "(\003\022\031\n\021userCreatedByName\030\003 \001(\t\022\023\n\013created" +
      "Date\030\004 \001(\t2\234\001\n\017TransferService\022\210\001\n\023getSt" +
      "ampInformation\0227.com.icheck.qr.read.grpc" +
      ".GrpcGetStampInformationRequest\0328.com.ic" +
      "heck.qr.read.grpc.GrpcGetStampInformatio" +
      "nResponseB\030\n\024com.vertx.vuong.grpcP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationRequest_descriptor,
        new java.lang.String[] { "Prefix", "IdStart", "IdEnd", "OwnerId", "ExcludeQr", });
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationResponse_descriptor,
        new java.lang.String[] { "Code", "Message", "Data", });
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icheck_qr_read_grpc_GrpcGetStampInformationData_descriptor,
        new java.lang.String[] { "CodeQRM", "CodeQRI", "CodeSMS", "Status", "BatchName", "ExportDate", "Services", "ProductName", "ProductImage", "Owner", "BatchId", "IsBlocked", "Prefix", "IdStart", "IdEnd", "InternalSerial", "InternalQRM", "InternalQRI", "InternalSMS", "RestoreInfo", });
    internal_static_com_icheck_qr_read_grpc_GrpcRestoreInfo_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_icheck_qr_read_grpc_GrpcRestoreInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_icheck_qr_read_grpc_GrpcRestoreInfo_descriptor,
        new java.lang.String[] { "Reason", "UserCreatedById", "UserCreatedByName", "CreatedDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
